name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    name: Linux Tests
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed

    steps:
      # Install Bash, Python, and Git
      - name: Install Bash, Python, and Git
        run: |
          zypper refresh
          zypper install -y bash python3 python3-pip git

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install pytest

      # Run pytest
      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest

      # Run Bash script tests
      - name: Run Bash script tests
        run: ./tests/shell/test_bible.sh

      # Run Markdown Update Script
      - name: Update Markdown
        run: python3 update_markdown.py

      # Run Shell Update Script
      - name: Update Shell
        run: python3 update_shell.py
