name: Windows CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  windows:
    name: Windows Tests
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Git with Git Bash
      - name: Install Git Bash
        run: |
          choco install git -y
          echo "Git Bash Installed"

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Run pytest
      - name: Run pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pytest

      # Run Bash script tests using Git Bash
      - name: Run Bash script tests (Git Bash)
        shell: bash
        run: ./tests/shell/test_bible.sh

      # Run Markdown Update Script
      - name: Update Markdown
        run: python update_markdown.py

      # Run Shell Update Script
      - name: Update Shell
        run: python update_shell.py
